services:
  - type: web
    name: vidstream
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: RAPIDAPI_KEY
        value: e9f2c625ebmsh6cd2de7109f2f5ep1f9991jsn4f3b636412b2
