server:
  port: ${PORT:10000}

spring:
  application:
    name: vidstream
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8

vidstream:
  temp-dir: ${VIDSTREAM_TEMP_DIR:/tmp/vidstream}
  ytdlp:
    path: ${YTDLP_PATH:yt-dlp}
  rapidapi:
    key: ${RAPIDAPI_KEY:e9f2c625ebmsh6cd2de7109f2f5ep1f9991jsn4f3b636412b2}
    download-host: ${RAPIDAPI_DOWNLOAD_HOST:youtube-mp36.p.rapidapi.com}

logging:
  level:
    com.vidstream: INFO
    org.springframework: WARN
